### ISSUE TITLE
Error	TS2661	Cannot re-export name that is not defined in the module.	node_modules\angular2\src\facade\promise.d.ts

### ISSUE THREAD

**Issue by kbio79** [Microsoft/build2016-vsmobile#1]
Any clues?

**Comment by kbio79** [comment]
I solve this problem by adding  declare var Promise: PromiseConstructor;  on the top of  promise.d.ts, problem is typescript 1.8

**Comment by rido-min** [comment]
This issue has been fixed with https://github.com/Microsoft/build2016-vsmobile/blob/master/_fixes/promise.d.ts
