### ISSUE TITLE
Impossible to run....

### ISSUE THREAD

**Issue by kbio79** [Microsoft/build2016-vsmobile#2]
![taco](https://cloud.githubusercontent.com/assets/6727841/14245153/9e121dbe-fa5f-11e5-8b02-46ecafd563cc.png)

**Comment by ridomin** [comment]
I assume all your packages are successfully restored (npm install)
looks like you need to run gulp tasks. Can you try to open the Task Runner and build again?  (you can also try from command line running gulp default).

You can check that the task ran successfully looking if you have files in the www/build folder.

To isolate potential Ripple issues I would try with the Android Emulator or Windows-x86, LocalMachine. 

Thanks
