### ISSUE TITLE
vs studio build error

### ISSUE THREAD

**Issue by koo9** [Microsoft/build2016-vsmobile#5]
got his error:

Severity    Code    Description Project File    Line    Suppression State
Error   TS2661  Build: Cannot re-export name that is not defined in the module. build2016-vsmobile  D:\Mobile Dev\build\node_modules\angular2\src\facade\promise.d.ts   1   

any idea?

**Comment by rido-min** [comment]
yes. this is a known issue with the version of angular. to avoid it you should replace the promise.d.ts with the one in the _fixes folder. It should be done by the npm scripts for you
