### ISSUE TITLE
Update to Ng 2 rc 1

### ISSUE THREAD

**Issue by mdelgadov** [Microsoft/build2016-vsmobile#8]
Hello and thanks for such great repository and your presentation in Build

I started with this example and even raised an issue that got solved by having 2 copies of the ng 2 polyfill, the min version (loaded at the beginning of index.html) and the normal version again at the end.

This is the way you have the index.html and providing a copy in the build, it fixed all problems.

Now, I moved to the ionic beta 7 that most importantly, uses Angular 2 rc 1, one of the requirements was to stop using the polifyll and start using zone and reflect. I tried to stop using the polyfill version at the beginning but still doesn't work.

So, I have the polyfill min version that is being called at run time when it wasn't supposed to being called. 
Of course, this is a bit confusing and even unpredictable.

My question is, why do the index needs the min copy of the polyfill and is there a way to avoid or change to something else...

Thanks in advance.

**Comment by ridomin** [comment]
Hi. the polyfill was a requirement for that version of angular. We are planning to update this sample to Beta 7. so stay tuned !!

**Comment by mdelgadov** [comment]
ok, thanks... counting the seconds!

and beta 8 is out... just saying...

**Comment by rido-min** [comment]
Updated to Beta10
